/*
 * Copyright (c) 2026, sakumisu
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef AVP_CONFIG_H
#define AVP_CONFIG_H

#ifndef CONFIG_AVP_DEBUG_MEMORY
#define CONFIG_AVP_DEBUG_MEMORY 0
#endif

#ifdef CONFIG_AVP_MP3_DSP_OVERRIDE_INCLUDE
#include CONFIG_AVP_MP3_DSP_OVERRIDE_INCLUDE
#endif

#ifdef CONFIG_AVP_AAC_DSP_OVERRIDE_INCLUDE
#include CONFIG_AVP_AAC_DSP_OVERRIDE_INCLUDE
#endif

#ifdef CONFIG_AVP_OPUS_CELT_DSP_OVERRIDE_INCLUDE
#include CONFIG_AVP_OPUS_CELT_DSP_OVERRIDE_INCLUDE
#endif

#ifdef CONFIG_AVP_OPUS_SILK_DSP_OVERRIDE_INCLUDE
#include CONFIG_AVP_OPUS_SILK_DSP_OVERRIDE_INCLUDE
#endif

#ifdef CONFIG_AVP_WEBRTC_DSP_OVERRIDE_INCLUDE
#include CONFIG_AVP_WEBRTC_DSP_OVERRIDE_INCLUDE
#endif

#endif
